export * from "./article.interface"
export * from "./article-preview.interface"
export * from "./articles-pagination-meta.interface"
export * from "./news-service-options.interface"
export * from "./next-data-page.interface"
